#!/usr/bin/env bash
##
## Anonymous Studio — OpenFGA seed script
##
## Creates the store, uploads model.fga, and writes demo authorization tuples.
## Run ONCE after `docker compose up -d` and waiting for the healthcheck.
##
## Usage:
##   bash seed.sh [--api http://localhost:8080]
##
## Output: writes OPENFGA_STORE_ID and OPENFGA_MODEL_ID to .env.openfga
## (which services/authz.py reads at startup).
##
set -euo pipefail

API="${OPENFGA_API_URL:-http://localhost:8080}"
ENV_FILE="$(dirname "$0")/.env.openfga"

echo "==> Waiting for OpenFGA API at $API …"
for i in $(seq 1 30); do
  if curl -sf "$API/healthz" > /dev/null 2>&1; then break; fi
  echo "    ($i/30) not ready yet, retrying in 2 s…"
  sleep 2
done
curl -sf "$API/healthz" > /dev/null || { echo "ERROR: OpenFGA not reachable at $API"; exit 1; }
echo "    OpenFGA is up."

# ── 1. Create store ──────────────────────────────────────────────────────────
echo "==> Creating store 'anonymous-studio'…"
STORE_RESP=$(curl -sf -X POST "$API/stores" \
  -H "Content-Type: application/json" \
  -d '{"name": "anonymous-studio"}')
STORE_ID=$(echo "$STORE_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "    Store ID: $STORE_ID"

# ── 2. Upload authorization model ────────────────────────────────────────────
echo "==> Uploading authorization model from model.fga…"
MODEL_DIR="$(dirname "$0")"
# Convert DSL to JSON using the fga CLI if available, else use pre-built JSON.
if command -v fga &> /dev/null; then
  MODEL_JSON=$(fga model transform --file "$MODEL_DIR/model.fga" --from dsl --to json)
else
  # Fallback: ship the JSON form alongside model.fga.
  MODEL_JSON=$(cat "$MODEL_DIR/model.json")
fi

MODEL_RESP=$(curl -sf -X POST "$API/stores/$STORE_ID/authorization-models" \
  -H "Content-Type: application/json" \
  -d "$MODEL_JSON")
MODEL_ID=$(echo "$MODEL_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['authorization_model_id'])")
echo "    Model ID: $MODEL_ID"

# ── 3. Write demo tuples ─────────────────────────────────────────────────────
echo "==> Writing demo authorization tuples…"
TUPLES_JSON=$(cat "$MODEL_DIR/seed_tuples.json")
curl -sf -X POST "$API/stores/$STORE_ID/write" \
  -H "Content-Type: application/json" \
  -d "{
    \"authorization_model_id\": \"$MODEL_ID\",
    \"writes\": $TUPLES_JSON
  }" > /dev/null
echo "    Tuples written."

# ── 4. Persist IDs ───────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by seed.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
OPENFGA_API_URL=$API
OPENFGA_STORE_ID=$STORE_ID
OPENFGA_MODEL_ID=$MODEL_ID
EOF
echo "==> Wrote $ENV_FILE"

echo ""
echo "Done! Add to your Anonymous Studio environment:"
echo "  export OPENFGA_ENABLED=true"
echo "  source $ENV_FILE"
echo ""
echo "Open the Studio: http://localhost:3000"
